EJERCICIOS = {
    "bajar_peso": [
        {"name": "Cinta de correr", "zone": "cardio", "image": "cinta_de_correr.png"},
        {"name": "Bicicleta estática", "zone": "cardio", "image": "bicicleta_estatica.png"},
        {"name": "Burpees", "zone": "fullbody", "image": "burpees.png"},
        {"name": "Jumping jacks", "zone": "cardio", "image": "jumping_jacks.png"},
        {"name": "Sentadillas", "zone": "piernas", "image": "sentadillas.png"},
        {"name": "Plancha", "zone": "core", "image": "plancha.png"},
        {"name": "Zancadas", "zone": "piernas", "image": "zancadas.png"},
        {"name": "Escaladores", "zone": "cardio", "image": "escaladores.png"},
        {"name": "Step-ups", "zone": "piernas", "image": "step_ups.png"},
        {"name": "Saltar la cuerda", "zone": "cardio", "image": "saltar_la_cuerda.png"},
        {"name": "Remo en máquina", "zone": "espalda", "image": "remo_en_maquina.png"},
        {"name": "Kettlebell swings", "zone": "fullbody", "image": "kettlebell_swings.png"},
        {"name": "Sprints cortos", "zone": "cardio", "image": "sprints_cortos.png"},
        {"name": "Skipping", "zone": "cardio", "image": "skipping.png"},
        {"name": "Mountain climbers", "zone": "cardio", "image": "mountain_climbers.png"},
        {"name": "High knees", "zone": "cardio", "image": "high_knees.png"},
        {"name": "Russian twists", "zone": "core", "image": "russian_twists.png"},
        {"name": "Jump lunges", "zone": "piernas", "image": "jump_lunges.png"},
        {"name": "Box jumps", "zone": "piernas", "image": "box_jumps.png"},
        {"name": "Shadow boxing", "zone": "cardio", "image": "shadow_boxing.png"}
    ],
    "volumen": [
        {"name": "Press de banca", "zone": "pecho", "image": "press_de_banca.png"},
        {"name": "Peso muerto", "zone": "espalda", "image": "peso_muerto.png"},
        {"name": "Sentadilla libre", "zone": "piernas", "image": "sentadilla_libre.png"},
        {"name": "Remo con barra", "zone": "espalda", "image": "remo_con_barra.png"},
        {"name": "Dominadas", "zone": "espalda", "image": "dominadas.png"},
        {"name": "Curl de bíceps", "zone": "brazos", "image": "curl_de_biceps.png"},
        {"name": "Press militar", "zone": "hombros", "image": "press_militar.png"},
        {"name": "Extensión de tríceps", "zone": "brazos", "image": "extension_de_triceps.png"},
        {"name": "Elevaciones laterales", "zone": "hombros", "image": "elevaciones_laterales.png"},
        {"name": "Prensa de piernas", "zone": "piernas", "image": "prensa_de_piernas.png"},
        {"name": "Fondos en paralelas", "zone": "pecho", "image": "fondos_en_paralelas.png"},
        {"name": "Remo en polea baja", "zone": "espalda", "image": "remo_en_polea_baja.png"},
        {"name": "Hip thrust", "zone": "gluteos", "image": "hip_thrust.png"},
        {"name": "Face pulls", "zone": "hombros", "image": "face_pulls.png"},
        {"name": "Pull-over", "zone": "pecho", "image": "pull_over.png"},
        {"name": "Split squat", "zone": "piernas", "image": "split_squat.png"},
        {"name": "Farmer's walk", "zone": "fullbody", "image": "farmers_walk.png"},
        {"name": "Good mornings", "zone": "espalda", "image": "good_mornings.png"},
        {"name": "Chest fly", "zone": "pecho", "image": "chest_fly.png"},
        {"name": "Dips", "zone": "pecho", "image": "dips.png"}
    ],
    "definicion": [
        {"name": "Press militar", "zone": "hombros", "image": "press_militar.png"},
        {"name": "Zancadas", "zone": "piernas", "image": "zancadas.png"},
        {"name": "Crunch abdominal", "zone": "core", "image": "crunch_abdominal.png"},
        {"name": "Elevaciones laterales", "zone": "hombros", "image": "elevaciones_laterales.png"},
        {"name": "Mountain climbers", "zone": "cardio", "image": "mountain_climbers.png"},
        {"name": "Fondos en paralelas", "zone": "pecho", "image": "fondos_en_paralelas.png"},
        {"name": "Plancha con toque de hombros", "zone": "core", "image": "plancha_toque_hombros.png"},
        {"name": "Flexiones diamantadas", "zone": "pecho", "image": "flexiones_diamantadas.png"},
        {"name": "Sentadilla con salto", "zone": "piernas", "image": "sentadilla_con_salto.png"},
        {"name": "Bicicleta abdominal", "zone": "core", "image": "bicicleta_abdominal.png"},
        {"name": "Escaladores cruzados", "zone": "cardio", "image": "escaladores_cruzados.png"},
        {"name": "Tríceps kickback con mancuernas", "zone": "brazos", "image": "triceps_kickback.png"},
        {"name": "Burpees con salto", "zone": "fullbody", "image": "burpees_con_salto.png"},
        {"name": "Plank jacks", "zone": "core", "image": "plank_jacks.png"},
        {"name": "Lateral bounds", "zone": "piernas", "image": "lateral_bounds.png"},
        {"name": "Renegade rows", "zone": "espalda", "image": "renegade_rows.png"},
        {"name": "Jump rope double unders", "zone": "cardio", "image": "double_unders.png"},
        {"name": "Box jumps explosivos", "zone": "piernas", "image": "box_jumps_explosivos.png"},
        {"name": "Russian twists con peso", "zone": "core", "image": "russian_twists_peso.png"},
        {"name": "Hollow holds", "zone": "core", "image": "hollow_holds.png"}
    ],
    "tonificar": [
        {"name": "Cinta de correr", "zone": "cardio", "image": "cinta_de_correr.png"},
        {"name": "Press militar", "zone": "hombros", "image": "press_militar.png"},
        {"name": "Zancadas", "zone": "piernas", "image": "zancadas.png"},
        {"name": "Plancha", "zone": "core", "image": "plancha.png"},
        {"name": "Burpees", "zone": "fullbody", "image": "burpees.png"},
        {"name": "Curl de bíceps", "zone": "brazos", "image": "curl_de_biceps.png"},
        {"name": "Elevaciones laterales", "zone": "hombros", "image": "elevaciones_laterales.png"},
        {"name": "Mountain climbers", "zone": "cardio", "image": "mountain_climbers.png"},
        {"name": "Step-ups", "zone": "piernas", "image": "step_ups.png"},
        {"name": "Remo en máquina", "zone": "espalda", "image": "remo_en_maquina.png"},
        {"name": "Crunch abdominal", "zone": "core", "image": "crunch_abdominal.png"},
        {"name": "Fondos", "zone": "pecho", "image": "fondos.png"}
    ],
    "flexibilidad": [
        {"name": "Estiramiento de isquiotibiales", "zone": "flexibilidad", "image": "estiramiento_isquiotibiales.png"},
        {"name": "Estiramiento de cuádriceps", "zone": "flexibilidad", "image": "estiramiento_cuadriceps.png"},
        {"name": "Cobra stretch", "zone": "flexibilidad", "image": "cobra_stretch.png"},
        {"name": "Child's pose", "zone": "flexibilidad", "image": "childs_pose.png"},
        {"name": "Puente de glúteos", "zone": "flexibilidad", "image": "puente_gluteos.png"},
        {"name": "Rotaciones de tronco", "zone": "flexibilidad", "image": "rotaciones_tronco.png"},
        {"name": "Estiramiento de hombros", "zone": "flexibilidad", "image": "estiramiento_hombros.png"},
        {"name": "Estiramiento de pectorales", "zone": "flexibilidad", "image": "estiramiento_pectorales.png"},
        {"name": "Estiramiento de gemelos", "zone": "flexibilidad", "image": "estiramiento_gemelos.png"},
        {"name": "Yoga - Saludo al sol", "zone": "flexibilidad", "image": "saludo_al_sol.png"},
        {"name": "Patada de glúteos dinámica", "zone": "flexibilidad", "image": "patada_gluteos_dinamica.png"},
        {"name": "Estiramiento lateral del torso", "zone": "flexibilidad", "image": "estiramiento_lateral_torso.png"}
    ]
}
